import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
program = "/bin/bash"

[window]
decorations = "full"
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10

# Key bindings for Ctrl+Shift+H, Ctrl+Shift+L, Ctrl+Shift+J, Ctrl+Shift+K

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;6u" # C-S-H

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;6u" # C-S-L

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;6u" # C-S-J

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;6u" # C-S-K

[[keyboard.bindings]]
key = "H"
mods = "Alt|Shift"
chars = "\u001bH"

[[keyboard.bindings]]
key = "L"
mods = "Alt|Shift"
chars = "\u001bL"
